<?php include('header.php'); ?>
<section id="content">
  <header>
    <h3>Introduction</h3>
  </header>
  <p><strong>On a holiday break,</strong> I was visiting my grandmother on my father's side.  My brother and I have an interest in video and film, and we though it would be cool to see what we could do with our grandmother's old 8mm film camera.  We asked if we could borrow the equipment, but instead she just gave it to us.  She also gave us the family films that they had shot over the years.  The collection consisted of 10 spools of 200 ft 8mm film.  Word then got to my mom's mother and she gave us the film she had, which was 59 spools of 50 ft Super8 film.  I suspected that the film was in good condition, but I also knew that the film would not last.  Now my paternal grandmother had transferred some of the film to VHS back in the late 80s, but, other than that, nothing had been done with the film.  I felt it was my duty as the family technophile to archive this film to a more stable state by digitizing it.</p>
  <p><strong>Being a man of ingenuity and a penny pincher,</strong> I thought it was a waste of money to pay someone to transfer the film.  I didn't trust a third party to properly transfer the film at a price I thought was reasonable.  So, I searched the Internet for a homemade solution.  I found three common ways to transfer the film.  First, a person can transfer film by playing the film on a standard projector and capturing the output on a camcorder.  This method is horrible because each frame is not captured, just the general motion of the film.  Second, a person can take a picture of each frame using a digital camera.  This is the best method in my opinion, but the cost of the equipment is a barrier.  If I was to pay someone to do the work for me, I would use this method.  But I was not going to pay someone, so my best option was to use the last method.  I planned on using a flatbed scanner, equipped with a transparent media adapter, to scan sections of the film and use a motorized system to advance the film for the next scan.  The film images could then be process by software to have the frames cut from the sections and saved as individual files.  The image files would then be complied into a single video file.</p>
  <p><strong>With the plan in place,</strong> all I had to do was learn how to do it.  Since I knew very little of film, scanners, motorization, computer control, or image manipulation, I had a large task ahead of me, but I stand here today to tell you it works.  It may be very impractical and not at all the best way to do it, but I created a system that turns film into video using a flatbed scanner.</p>
</section>
<?php include('footer.php'); ?>
